<Project Sdk="Microsoft.NET.Sdk">

  

  

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Result.FluentValidation\EricksonLopez.Result.FluentValidation.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Result.Testing\EricksonLopez.Result.Testing.csproj" />
  </ItemGroup>

</Project>
