sonar.sources=src
sonar.tests=tests
sonar.exclusions=samples/**,benchmarks/**,scripts/**,**/bin/**,**/obj/**,**/*.js
sonar.test.exclusions=tests/**,**/*Tests.cs,**/*Test*.cs
sonar.cpd.exclusions=tests/**,**/tests/**,**/*Tests.cs,**/*Test*.cs,**/samples/**,**/benchmarks/**,**/bin/**,**/obj/**,**/Result.Combine.cs,**/Result.ValidateAll.cs,**/Result.cs,**/ResultOfT.cs,**/ResultExtensions*.cs,**/ResultSyncExtensions.cs,**/ResultActivityExtensions.cs,**/*JsonConverter*.cs,**/*Analyzer*.cs