<Project Sdk="Microsoft.NET.Sdk">
  <!-- Copyright © Erickson Lopez. MIT License. -->
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <AssemblyName>EricksonLopez.Result.Generic</AssemblyName>
    <RootNamespace>EricksonLopez.Result.Generic</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageId>EricksonLopez.Result.Generic</PackageId>
    <Authors>Erickson Lopez</Authors>
    <Company>Erickson Lopez</Company>
    <Copyright>Copyright © 2026 Erickson Lopez</Copyright>
    <Description>Strongly-typed Result&lt;TValue, TError&gt; with compile-time error types for strict domain model pipelines in modern .NET.</Description>
    <PackageProjectUrl>https://ericksonlopez.dev/result</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ericksonlopezf/dotnet-result</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageTags>$(CommonPackageTags);generic;strongly-typed;typed-error;domain-errors;domain-driven-design;ddd;monad;struct;zero-allocation;native-aot</PackageTags>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAotCompatible>true</IsAotCompatible>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EricksonLopez.Result\EricksonLopez.Result.csproj" />
  </ItemGroup>
</Project>
