<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Result.Serialization\EricksonLopez.Result.Serialization.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Result.Testing\EricksonLopez.Result.Testing.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Result.Serialization.Generators\EricksonLopez.Result.Serialization.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
  </ItemGroup>
</Project>
