<Project Sdk="Microsoft.NET.Sdk">
  <!-- Copyright © Erickson Lopez. MIT License. -->
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <SonarQubeTestProject>true</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Result.Testing.XUnit\EricksonLopez.Result.Testing.XUnit.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Result.Serialization.Generators\EricksonLopez.Result.Serialization.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\EricksonLopez.Result\EricksonLopez.Result.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Result.Testing\EricksonLopez.Result.Testing.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Result.OpenTelemetry\EricksonLopez.Result.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Result.AspNetCore\EricksonLopez.Result.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\EricksonLopez.Result.Serialization\EricksonLopez.Result.Serialization.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="xunit.runner.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <PropertyGroup>
    <Include>[EricksonLopez.Result]*,[EricksonLopez.Result.*]*</Include>
    <Exclude>[EricksonLopez.Result.Analyzers]*,[EricksonLopez.Result.Serialization.Generators]*</Exclude>
  </PropertyGroup>
</Project>
